\if :{?repo_root}
\else
\set repo_root /workspace
\endif
\set ON_ERROR_STOP on
\pset pager off
\timing on

\connect blogapp_lab
DROP DATABASE IF EXISTS stackexchange WITH (FORCE);
CREATE DATABASE stackexchange OWNER labuser;
\connect stackexchange

\echo '=== LAB 05 - extensions ==='
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS file_fdw;
CREATE EXTENSION IF NOT EXISTS postgres_fdw;

\echo '=== Schema Stack Exchange partitionne correctement ==='
CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    reputation INTEGER NOT NULL DEFAULT 1,
    creation_date TIMESTAMP NOT NULL,
    display_name VARCHAR(100),
    last_access_date TIMESTAMP,
    location VARCHAR(200),
    about_me TEXT,
    views INTEGER NOT NULL DEFAULT 0,
    up_votes INTEGER NOT NULL DEFAULT 0,
    down_votes INTEGER NOT NULL DEFAULT 0,
    account_id INTEGER
);

-- Cette table garantit l unicite globale des IDs, impossible a imposer
-- directement sur une table partitionnee par creation_date.
CREATE TABLE post_ids (
    id INTEGER PRIMARY KEY,
    creation_date TIMESTAMP NOT NULL,
    UNIQUE (id, creation_date)
);

CREATE TABLE posts (
    id INTEGER NOT NULL,
    post_type_id SMALLINT NOT NULL,
    parent_id INTEGER,
    accepted_answer_id INTEGER,
    creation_date TIMESTAMP NOT NULL,
    score INTEGER NOT NULL DEFAULT 0,
    view_count INTEGER NOT NULL DEFAULT 0,
    body TEXT,
    owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    last_editor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    last_edit_date TIMESTAMP,
    last_activity_date TIMESTAMP,
    title VARCHAR(250),
    tags VARCHAR(250),
    answer_count INTEGER NOT NULL DEFAULT 0,
    comment_count INTEGER NOT NULL DEFAULT 0,
    favorite_count INTEGER NOT NULL DEFAULT 0,
    community_owned_date TIMESTAMP,
    search_vector TSVECTOR,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    visibility VARCHAR(20) NOT NULL DEFAULT 'public',
    tenant_id INTEGER,
    PRIMARY KEY (id, creation_date),
    CONSTRAINT fk_posts_identite
        FOREIGN KEY (id, creation_date)
        REFERENCES post_ids(id, creation_date)
        ON DELETE CASCADE,
    CONSTRAINT chk_posts_visibility
        CHECK (visibility IN ('public', 'private', 'moderation'))
) PARTITION BY RANGE (creation_date);

DO $$
DECLARE
    annee INTEGER;
BEGIN
    FOR annee IN 2015..2024 LOOP
        EXECUTE format(
            'CREATE TABLE posts_%s PARTITION OF posts FOR VALUES FROM (%L) TO (%L)',
            annee,
            make_date(annee, 1, 1),
            make_date(annee + 1, 1, 1)
        );
    END LOOP;
END;
$$;

CREATE TABLE posts_default PARTITION OF posts DEFAULT;

CREATE TABLE comments (
    id INTEGER PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES post_ids(id) ON DELETE CASCADE,
    score INTEGER NOT NULL DEFAULT 0,
    text TEXT NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE votes (
    id INTEGER PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES post_ids(id) ON DELETE CASCADE,
    vote_type_id SMALLINT NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    bounty_amount INTEGER
);

CREATE TABLE badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT NOW(),
    class SMALLINT,
    tag_based BOOLEAN NOT NULL DEFAULT FALSE,
    details JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE tags (
    id INTEGER PRIMARY KEY,
    tag_name VARCHAR(50) NOT NULL UNIQUE,
    count INTEGER NOT NULL DEFAULT 0,
    excerpt_post_id INTEGER,
    wiki_post_id INTEGER
);

CREATE TABLE post_tags (
    post_id INTEGER NOT NULL REFERENCES post_ids(id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

\echo '=== Import du vrai dump Coffee Stack Exchange ==='
\copy users (id, reputation, creation_date, display_name, last_access_date, location, about_me, views, up_votes, down_votes, account_id) FROM 'data/stackexchange-coffee/csv/users.csv' WITH (FORMAT csv, HEADER true)
\copy post_ids (id, creation_date) FROM 'data/stackexchange-coffee/csv/post_ids.csv' WITH (FORMAT csv, HEADER true)
\copy posts (id, post_type_id, parent_id, accepted_answer_id, creation_date, score, view_count, body, owner_user_id, last_editor_user_id, last_edit_date, last_activity_date, title, tags, answer_count, comment_count, favorite_count, community_owned_date) FROM 'data/stackexchange-coffee/csv/posts.csv' WITH (FORMAT csv, HEADER true)
\copy comments (id, post_id, score, text, creation_date, user_id) FROM 'data/stackexchange-coffee/csv/comments.csv' WITH (FORMAT csv, HEADER true)
\copy votes (id, post_id, vote_type_id, creation_date, user_id, bounty_amount) FROM 'data/stackexchange-coffee/csv/votes.csv' WITH (FORMAT csv, HEADER true)
\copy badges (id, user_id, name, date, class, tag_based) FROM 'data/stackexchange-coffee/csv/badges.csv' WITH (FORMAT csv, HEADER true)
\copy tags (id, tag_name, count, excerpt_post_id, wiki_post_id) FROM 'data/stackexchange-coffee/csv/tags.csv' WITH (FORMAT csv, HEADER true)
\copy post_tags (post_id, tag_id) FROM 'data/stackexchange-coffee/csv/post_tags.csv' WITH (FORMAT csv, HEADER true)

SELECT setval(
    pg_get_serial_sequence('badges', 'id'),
    GREATEST((SELECT MAX(id) FROM badges), 1)
);

ANALYZE;

SELECT 'users' AS table_name, COUNT(*) AS lignes FROM users
UNION ALL SELECT 'posts', COUNT(*) FROM posts
UNION ALL SELECT 'comments', COUNT(*) FROM comments
UNION ALL SELECT 'votes', COUNT(*) FROM votes
UNION ALL SELECT 'badges', COUNT(*) FROM badges
UNION ALL SELECT 'tags', COUNT(*) FROM tags
UNION ALL SELECT 'post_tags', COUNT(*) FROM post_tags
ORDER BY table_name;

SELECT
    tableoid::regclass AS partition,
    COUNT(*) AS lignes
FROM posts
GROUP BY tableoid
ORDER BY 1;

\echo '=== Index de recherche et de filtrage ==='
CREATE INDEX idx_posts_search_vector ON posts USING GIN(search_vector);
CREATE INDEX idx_posts_title_trgm_gist ON posts USING GIST(title gist_trgm_ops);
CREATE INDEX idx_posts_score ON posts(score);
CREATE INDEX idx_posts_type_date ON posts(post_type_id, creation_date DESC);
CREATE INDEX idx_posts_owner ON posts(owner_user_id);
CREATE INDEX idx_posts_unanswered
    ON posts(creation_date DESC)
    WHERE post_type_id = 1 AND accepted_answer_id IS NULL;
CREATE INDEX idx_posts_creation_brin ON posts USING BRIN(creation_date);
CREATE INDEX idx_users_lower_name ON users(lower(display_name));
CREATE INDEX idx_comments_post ON comments(post_id);
CREATE INDEX idx_votes_post_type ON votes(post_id, vote_type_id);
CREATE INDEX idx_post_tags_tag ON post_tags(tag_id);

\echo '=== Exercice 4.7 - migration des votes vers des partitions mensuelles ==='
ALTER TABLE votes RENAME TO votes_old;
CREATE TABLE votes (
    id INTEGER NOT NULL,
    post_id INTEGER NOT NULL REFERENCES post_ids(id) ON DELETE CASCADE,
    vote_type_id SMALLINT NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    bounty_amount INTEGER,
    PRIMARY KEY (id, creation_date)
) PARTITION BY RANGE (creation_date);

DO $$
DECLARE
    mois INTEGER;
    debut DATE;
    fin DATE;
BEGIN
    FOR mois IN 1..12 LOOP
        debut := make_date(2023, mois, 1);
        fin := (debut + INTERVAL '1 month')::date;
        EXECUTE format(
            'CREATE TABLE votes_2023_%s PARTITION OF votes FOR VALUES FROM (%L) TO (%L)',
            to_char(mois, 'FM00'), debut, fin
        );
    END LOOP;
END;
$$;

CREATE TABLE votes_default PARTITION OF votes DEFAULT;
CREATE INDEX idx_votes_migrees_post ON votes(post_id, vote_type_id);

INSERT INTO votes
SELECT * FROM votes_old;

SELECT tableoid::regclass AS partition, COUNT(*) AS lignes
FROM votes
GROUP BY tableoid
ORDER BY 1;

EXPLAIN (ANALYZE, BUFFERS, COSTS OFF)
SELECT COUNT(*)
FROM votes
WHERE creation_date >= TIMESTAMP '2023-06-01'
  AND creation_date < TIMESTAMP '2023-07-01';

\echo '=== Partie 5 - fonctions PL/pgSQL et triggers ==='
CREATE OR REPLACE FUNCTION calculate_user_reputation(p_user_id INTEGER)
RETURNS INTEGER
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_upvotes INTEGER;
    v_downvotes INTEGER;
    v_reponses_acceptees INTEGER;
    v_total INTEGER;
BEGIN
    SELECT
        COUNT(*) FILTER (WHERE v.vote_type_id = 2),
        COUNT(*) FILTER (WHERE v.vote_type_id = 3)
    INTO v_upvotes, v_downvotes
    FROM votes v
    JOIN posts p ON p.id = v.post_id
    WHERE p.owner_user_id = p_user_id;

    SELECT COUNT(*)
    INTO v_reponses_acceptees
    FROM posts reponse
    WHERE reponse.owner_user_id = p_user_id
      AND reponse.post_type_id = 2
      AND EXISTS (
          SELECT 1
          FROM posts question
          WHERE question.accepted_answer_id = reponse.id
      );

    v_total := COALESCE(v_upvotes, 0) * 10
             - COALESCE(v_downvotes, 0) * 2
             + COALESCE(v_reponses_acceptees, 0) * 15;
    RETURN GREATEST(v_total, 1);
END;
$$;

SELECT
    id,
    display_name,
    reputation AS reputation_stockee,
    calculate_user_reputation(id) AS reputation_calculee
FROM users
ORDER BY reputation DESC
LIMIT 5;

CREATE OR REPLACE FUNCTION get_question_thread(p_question_id INTEGER)
RETURNS TABLE (
    post_id INTEGER,
    post_type TEXT,
    author VARCHAR,
    content TEXT,
    score INTEGER,
    created_at TIMESTAMP
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    RETURN QUERY
    SELECT
        p.id,
        CASE p.post_type_id WHEN 1 THEN 'Question' ELSE 'Answer' END::TEXT,
        u.display_name,
        p.body,
        p.score,
        p.creation_date
    FROM posts p
    LEFT JOIN users u ON u.id = p.owner_user_id
    WHERE (p.id = p_question_id AND p.post_type_id = 1)
       OR (p.parent_id = p_question_id AND p.post_type_id = 2)
    ORDER BY CASE WHEN p.id = p_question_id THEN 0 ELSE 1 END,
             p.creation_date,
             p.id;
END;
$$;

SELECT post_id, post_type, author, score, created_at
FROM get_question_thread((SELECT MIN(id) FROM posts WHERE post_type_id = 1));

-- Pas de clause WHEN avec NEW et OLD melanges : NEW n existe pas sur DELETE.


CREATE TABLE posts_audit (
    audit_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    post_id INTEGER,
    operation TEXT NOT NULL,
    old_data JSONB,
    new_data JSONB,
    changed_by TEXT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION audit_posts()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO posts_audit (post_id, operation, new_data, changed_by)
        VALUES (NEW.id, TG_OP, to_jsonb(NEW), current_user);
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO posts_audit (post_id, operation, old_data, new_data, changed_by)
        VALUES (NEW.id, TG_OP, to_jsonb(OLD), to_jsonb(NEW), current_user);
    ELSE
        INSERT INTO posts_audit (post_id, operation, old_data, changed_by)
        VALUES (OLD.id, TG_OP, to_jsonb(OLD), current_user);
    END IF;
    RETURN NULL;
END;
$$;



CREATE OR REPLACE FUNCTION safe_divide(p_numerateur NUMERIC, p_denominateur NUMERIC)
RETURNS NUMERIC
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    IF p_denominateur = 0 THEN
        RETURN NULL;
    END IF;
    RETURN p_numerateur / p_denominateur;
END;
$$;

SELECT safe_divide(10, 2) AS division_valide,
       safe_divide(10, 0) AS division_par_zero;

\echo '=== Exercice 5.8 - attribution automatique de badges ==='
CREATE OR REPLACE FUNCTION check_and_award_badges(p_user_id INTEGER)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_user_id IS NULL THEN
        RETURN;
    END IF;
    -- Une attribution à la fois par utilisateur ; pas de doublon concurrent.
    PERFORM pg_advisory_xact_lock(73412, p_user_id);

    IF EXISTS (
        SELECT 1
        FROM posts reponse
        WHERE reponse.owner_user_id = p_user_id
          AND reponse.post_type_id = 2
          AND EXISTS (
              SELECT 1 FROM posts question
              WHERE question.accepted_answer_id = reponse.id
          )
    ) AND NOT EXISTS (
        SELECT 1 FROM badges WHERE user_id = p_user_id AND name = 'Scholar'
    ) THEN
        INSERT INTO badges (user_id, name, class) VALUES (p_user_id, 'Scholar', 3);
    END IF;

    IF EXISTS (
        SELECT 1 FROM votes WHERE user_id = p_user_id AND vote_type_id = 2
    ) AND NOT EXISTS (
        SELECT 1 FROM badges WHERE user_id = p_user_id AND name = 'Supporter'
    ) THEN
        INSERT INTO badges (user_id, name, class) VALUES (p_user_id, 'Supporter', 3);
    END IF;

    IF EXISTS (
        SELECT 1 FROM votes WHERE user_id = p_user_id AND vote_type_id = 3
    ) AND NOT EXISTS (
        SELECT 1 FROM badges WHERE user_id = p_user_id AND name = 'Critic'
    ) THEN
        INSERT INTO badges (user_id, name, class) VALUES (p_user_id, 'Critic', 3);
    END IF;

    IF EXISTS (
        SELECT 1 FROM posts
        WHERE owner_user_id = p_user_id
          AND post_type_id = 2
          AND score >= 10
    ) AND NOT EXISTS (
        SELECT 1 FROM badges WHERE user_id = p_user_id AND name = 'Nice Answer'
    ) THEN
        INSERT INTO badges (user_id, name, class) VALUES (p_user_id, 'Nice Answer', 3);
    END IF;

    IF EXISTS (
        SELECT 1 FROM posts
        WHERE owner_user_id = p_user_id
          AND post_type_id = 1
          AND view_count >= 1000
    ) AND NOT EXISTS (
        SELECT 1 FROM badges WHERE user_id = p_user_id AND name = 'Popular Question'
    ) THEN
        INSERT INTO badges (user_id, name, class) VALUES (p_user_id, 'Popular Question', 3);
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION trigger_award_badges_from_vote()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_owner_id INTEGER;
BEGIN
    PERFORM check_and_award_badges(NEW.user_id);
    SELECT owner_user_id INTO v_owner_id FROM posts WHERE id = NEW.post_id;
    PERFORM check_and_award_badges(v_owner_id);
    RETURN NULL;
END;
$$;

CREATE TRIGGER trig_award_badges_vote
AFTER INSERT ON votes
FOR EACH ROW EXECUTE FUNCTION trigger_award_badges_from_vote();

SELECT check_and_award_badges(id)
FROM users
ORDER BY reputation DESC
LIMIT 10;

\echo '=== Partie 6 - JSONB avance ==='
UPDATE posts p
SET metadata = jsonb_build_object(
    'language', 'en',
    'edited', p.last_edit_date IS NOT NULL,
    'has_code', COALESCE(p.body, '') ILIKE '%<code>%',
    'tag_count', (SELECT COUNT(*) FROM post_tags pt WHERE pt.post_id = p.id),
    'word_count', cardinality(
        regexp_split_to_array(
            trim(regexp_replace(COALESCE(p.body, ''), '<[^>]+>', ' ', 'g')),
            '\s+'
        )
    )
)
WHERE p.post_type_id = 1;

CREATE INDEX idx_posts_metadata_gin ON posts USING GIN(metadata);
CREATE INDEX idx_posts_metadata_language ON posts ((metadata->>'language'));

SELECT
    id,
    title,
    metadata->>'language' AS langue,
    (metadata->>'tag_count')::INTEGER AS nombre_tags,
    (metadata->>'word_count')::INTEGER AS nombre_mots
FROM posts
WHERE post_type_id = 1
ORDER BY view_count DESC
LIMIT 5;

-- Demonstration pgcrypto : le chiffrement est stocke en BYTEA, pas dans la colonne TEXT.
CREATE TABLE user_secrets (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    about_me_encrypted BYTEA NOT NULL
);

SELECT set_config('app.demo_encryption_key', encode(gen_random_bytes(32), 'hex'), false) IS NOT NULL AS cle_de_demo_chargee;
INSERT INTO user_secrets (user_id, about_me_encrypted)
SELECT id, pgp_sym_encrypt(about_me, current_setting('app.demo_encryption_key'))
FROM users
WHERE id = (SELECT MIN(id) FROM users WHERE about_me IS NOT NULL);

SELECT
    us.user_id,
    pgp_sym_decrypt(
        us.about_me_encrypted,
        current_setting('app.demo_encryption_key')
    ) = u.about_me AS dechiffrement_valide
FROM user_secrets us
JOIN users u ON u.id = us.user_id;

\echo '=== Partie 7 - analyse et optimisation ==='
VACUUM ANALYZE posts;
VACUUM ANALYZE comments;
VACUUM ANALYZE votes;

SHOW shared_buffers;
SHOW work_mem;
SHOW maintenance_work_mem;
SHOW effective_cache_size;
SHOW random_page_cost;

\echo '--- Plan de la requete avec sous-requetes correlees ---'
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF)
SELECT
    p.id,
    p.title,
    u.display_name AS auteur,
    (SELECT COUNT(*) FROM comments c WHERE c.post_id = p.id) AS commentaires,
    (SELECT COUNT(*) FROM votes v WHERE v.post_id = p.id AND v.vote_type_id = 2) AS upvotes
FROM posts p
LEFT JOIN users u ON u.id = p.owner_user_id
WHERE p.post_type_id = 1
  AND p.creation_date >= (SELECT MAX(creation_date) FROM posts) - INTERVAL '1 year'
ORDER BY upvotes DESC, p.id
LIMIT 100;

\echo '--- Version optimisee : candidats puis agregations ---'
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF)
WITH candidats AS MATERIALIZED (
    SELECT p.id, p.title, p.owner_user_id
    FROM posts p
    WHERE p.post_type_id = 1
      AND p.creation_date >= (SELECT MAX(creation_date) FROM posts) - INTERVAL '1 year'
), upvotes AS (
    SELECT v.post_id, COUNT(*) AS nombre
    FROM votes v
    JOIN candidats x ON x.id = v.post_id
    WHERE v.vote_type_id = 2
    GROUP BY v.post_id
), premiers AS MATERIALIZED (
    SELECT x.*, COALESCE(v.nombre, 0) AS upvotes
    FROM candidats x LEFT JOIN upvotes v ON v.post_id = x.id
    ORDER BY upvotes DESC, x.id LIMIT 100
), commentaires AS (
    SELECT c.post_id, COUNT(*) AS nombre
    FROM comments c JOIN premiers x ON x.id = c.post_id
    GROUP BY c.post_id
)
SELECT
    x.id,
    x.title,
    u.display_name AS auteur,
    COALESCE(c.nombre, 0) AS commentaires,
    x.upvotes
FROM premiers x
LEFT JOIN users u ON u.id = x.owner_user_id
LEFT JOIN commentaires c ON c.post_id = x.id
ORDER BY x.upvotes DESC, x.id;

\echo '=== Partie 8 - Row-Level Security multi-tenant ==='
CREATE TABLE tenants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO tenants (name)
VALUES ('Cafe Alpha'), ('Cafe Beta');

UPDATE posts
SET tenant_id = CASE WHEN id % 2 = 0 THEN 1 ELSE 2 END;

ALTER TABLE posts
    ADD CONSTRAINT fk_posts_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id);

CREATE OR REPLACE FUNCTION current_tenant_id()
RETURNS INTEGER
LANGUAGE sql
STABLE
AS $$
    SELECT NULLIF(current_setting('app.current_tenant_id', true), '')::INTEGER
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tenant_reader') THEN
        CREATE ROLE tenant_reader NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lab_admin') THEN
        CREATE ROLE lab_admin NOLOGIN;
    END IF;
END;
$$;

GRANT CONNECT ON DATABASE stackexchange TO tenant_reader, lab_admin;
GRANT USAGE ON SCHEMA public TO tenant_reader, lab_admin;
GRANT SELECT ON posts TO tenant_reader, lab_admin;

ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY posts_tenant_select
ON posts
FOR SELECT
TO tenant_reader
USING (tenant_id = current_tenant_id());

CREATE POLICY posts_admin_select
ON posts
FOR SELECT
TO lab_admin
USING (TRUE);

SELECT set_config('app.current_tenant_id', '1', false);
SET ROLE tenant_reader;
SELECT current_user AS role_test, current_tenant_id() AS tenant, COUNT(*) AS posts_visibles
FROM posts;
RESET ROLE;

SELECT set_config('app.current_tenant_id', '2', false);
SET ROLE tenant_reader;
SELECT current_user AS role_test, current_tenant_id() AS tenant, COUNT(*) AS posts_visibles
FROM posts;
RESET ROLE;

SET ROLE lab_admin;
SELECT current_user AS role_test, COUNT(*) AS tous_les_posts FROM posts;
RESET ROLE;

\set tags_csv :repo_root '/sql/tags_enriched.csv'
\echo '=== Partie 9 - Federation avec file_fdw ==='
CREATE SERVER lab_csv_server
FOREIGN DATA WRAPPER file_fdw;

CREATE FOREIGN TABLE tags_enriched_external (
    tag_name VARCHAR(50),
    description TEXT,
    category VARCHAR(50)
)
SERVER lab_csv_server
OPTIONS (
    filename :'tags_csv',
    format 'csv',
    header 'true'
);

CREATE TABLE post_stats (
    post_id INTEGER PRIMARY KEY REFERENCES post_ids(id) ON DELETE CASCADE,
    page_views BIGINT NOT NULL,
    bounce_rate NUMERIC(5,2) NOT NULL CHECK (bounce_rate BETWEEN 0 AND 100)
);

INSERT INTO post_stats (post_id, page_views, bounce_rate)
SELECT
    p.id,
    p.view_count * 2 + 100,
    round((20 + (p.id % 55))::numeric, 2)
FROM posts p
WHERE p.post_type_id = 1
ORDER BY p.view_count DESC
LIMIT 500;

CREATE MATERIALIZED VIEW dashboard_posts AS
SELECT
    p.id AS post_id,
    p.title,
    p.score,
    u.display_name AS auteur,
    string_agg(DISTINCT t.tag_name, ', ' ORDER BY t.tag_name) AS tags,
    string_agg(DISTINCT te.description, ' | ' ORDER BY te.description) AS descriptions_tags,
    ps.page_views,
    ps.bounce_rate
FROM posts p
LEFT JOIN users u ON u.id = p.owner_user_id
LEFT JOIN post_tags pt ON pt.post_id = p.id
LEFT JOIN tags t ON t.id = pt.tag_id
LEFT JOIN tags_enriched_external te ON te.tag_name = t.tag_name
LEFT JOIN post_stats ps ON ps.post_id = p.id
WHERE p.post_type_id = 1
GROUP BY p.id, p.title, p.score, u.display_name, ps.page_views, ps.bounce_rate;

CREATE UNIQUE INDEX idx_dashboard_posts_id ON dashboard_posts(post_id);
REFRESH MATERIALIZED VIEW dashboard_posts;

SELECT *
FROM dashboard_posts
WHERE descriptions_tags IS NOT NULL
ORDER BY page_views DESC NULLS LAST
LIMIT 10;

\echo '=== Projet final - cache, suggestions et journal de recherche ==='
CREATE TABLE search_cache (
    query_hash CHAR(64) PRIMARY KEY,
    query_text TEXT NOT NULL,
    filters JSONB NOT NULL DEFAULT '{}'::jsonb,
    page INTEGER NOT NULL,
    page_size INTEGER NOT NULL,
    results JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    hits INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX idx_search_cache_created ON search_cache(created_at);

CREATE TABLE search_suggestions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    suggestion TEXT NOT NULL UNIQUE,
    frequency INTEGER NOT NULL DEFAULT 1,
    last_used TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_search_suggestions_trgm
ON search_suggestions USING GIST (suggestion gist_trgm_ops);

CREATE TABLE search_log (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    query_text TEXT NOT NULL,
    filters JSONB NOT NULL,
    result_count INTEGER NOT NULL,
    cache_hit BOOLEAN NOT NULL,
    duration_ms NUMERIC(12,3) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION get_trending_tags(
    p_time_window INTERVAL DEFAULT INTERVAL '30 days'
)
RETURNS TABLE (
    tag VARCHAR,
    post_count BIGINT,
    total_views BIGINT
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        t.tag_name,
        COUNT(DISTINCT p.id),
        COALESCE(SUM(p.view_count), 0)::BIGINT
    FROM tags t
    JOIN post_tags pt ON pt.tag_id = t.id
    JOIN posts p ON p.id = pt.post_id
    WHERE p.post_type_id = 1
      AND p.creation_date >= CURRENT_TIMESTAMP - p_time_window
    GROUP BY t.id, t.tag_name
    ORDER BY 2 DESC, 3 DESC, t.tag_name
    LIMIT 20
$$;

CREATE MATERIALIZED VIEW search_analytics AS
SELECT
    date_trunc('hour', created_at) AS heure,
    query_text,
    COUNT(*) AS nombre_recherches,
    ROUND(AVG(duration_ms), 3) AS duree_moyenne_ms,
    ROUND(100.0 * COUNT(*) FILTER (WHERE cache_hit) / COUNT(*), 2) AS taux_cache_pct,
    SUM(result_count) AS resultats_retournes
FROM search_log
GROUP BY date_trunc('hour', created_at), query_text;

CREATE UNIQUE INDEX idx_search_analytics_unique
ON search_analytics(heure, query_text);

REFRESH MATERIALIZED VIEW search_analytics;
SELECT * FROM search_analytics ORDER BY heure DESC, nombre_recherches DESC;

\echo '=== Verification finale ==='
SELECT extname, extversion FROM pg_extension ORDER BY extname;

SELECT
    relname,
    pg_size_pretty(pg_total_relation_size(relid)) AS taille_totale,
    n_live_tup
FROM pg_stat_user_tables
ORDER BY pg_total_relation_size(relid) DESC
LIMIT 15;

SELECT schemaname, tablename, indexname
FROM pg_indexes
WHERE schemaname = 'public'
  AND (
      indexname LIKE '%search%'
      OR indexname LIKE '%trgm%'
      OR indexname LIKE '%metadata%'
      OR indexname LIKE '%brin%'
  )
ORDER BY tablename, indexname;

SELECT polname, polroles::regrole[], polcmd, pg_get_expr(polqual, polrelid) AS condition
FROM pg_policy
WHERE polrelid = 'posts'::regclass
ORDER BY polname;

\echo '=== Recherche multilingue et filtres communs ==='
CREATE FUNCTION search_config_for(p_language TEXT) RETURNS regconfig
LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE lower(COALESCE(p_language, 'en'))
        WHEN 'fr' THEN 'french'::regconfig WHEN 'french' THEN 'french'::regconfig
        WHEN 'de' THEN 'german'::regconfig WHEN 'german' THEN 'german'::regconfig
        WHEN 'es' THEN 'spanish'::regconfig WHEN 'spanish' THEN 'spanish'::regconfig
        ELSE 'english'::regconfig END
$$;
ALTER TABLE posts ADD COLUMN search_config regconfig NOT NULL DEFAULT 'english';
CREATE OR REPLACE FUNCTION posts_search_vector_update() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.search_config := search_config_for(NEW.metadata->>'language');
    NEW.search_vector :=
        setweight(to_tsvector(NEW.search_config, COALESCE(NEW.title, '')), 'A') ||
        setweight(to_tsvector(NEW.search_config,
            regexp_replace(COALESCE(NEW.body, ''), '<[^>]+>', ' ', 'g')), 'B');
    RETURN NEW;
END $$;

CREATE TRIGGER trig_posts_search_vector_update
BEFORE INSERT OR UPDATE OF title, body, metadata ON posts
FOR EACH ROW EXECUTE FUNCTION posts_search_vector_update();
UPDATE posts SET metadata = metadata;

-- Une erreur de type est signalée : un filtre mal formé ne doit pas être ignoré.
CREATE FUNCTION validate_search_filters(f JSONB) RETURNS void
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE k TEXT; n NUMERIC;
BEGIN
    IF jsonb_typeof(f) IS DISTINCT FROM 'object' THEN
        RAISE EXCEPTION 'Les filtres doivent former un objet JSON' USING ERRCODE='22023';
    END IF;
    FOR k IN SELECT jsonb_object_keys(f) LOOP
        IF k NOT IN ('tags','min_score','has_accepted_answer','date_range',
                     'date_from','date_to','language','metadata') THEN
            RAISE EXCEPTION 'Filtre inconnu : %', k USING ERRCODE='22023';
        END IF;
    END LOOP;
    IF f ? 'tags' THEN
        IF jsonb_typeof(f->'tags') IS DISTINCT FROM 'array' THEN
            RAISE EXCEPTION 'tags doit etre un tableau' USING ERRCODE='22023';
        END IF;
        IF EXISTS (SELECT FROM jsonb_array_elements(f->'tags') x
                   WHERE jsonb_typeof(x) <> 'string') THEN
            RAISE EXCEPTION 'Chaque tag doit etre une chaine' USING ERRCODE='22023';
        END IF;
    END IF;
    IF f ? 'min_score' THEN
        IF jsonb_typeof(f->'min_score') IS DISTINCT FROM 'number' THEN
            RAISE EXCEPTION 'min_score doit etre un entier' USING ERRCODE='22023';
        END IF;
        n := (f->>'min_score')::numeric;
        IF n <> trunc(n) OR n NOT BETWEEN -2147483648 AND 2147483647 THEN
            RAISE EXCEPTION 'min_score hors limites' USING ERRCODE='22023';
        END IF;
    END IF;
    IF f ? 'has_accepted_answer' AND
       jsonb_typeof(f->'has_accepted_answer') IS DISTINCT FROM 'boolean' THEN
        RAISE EXCEPTION 'has_accepted_answer doit etre un booleen' USING ERRCODE='22023';
    END IF;
    IF f ? 'metadata' AND jsonb_typeof(f->'metadata') IS DISTINCT FROM 'object' THEN
        RAISE EXCEPTION 'metadata doit etre un objet' USING ERRCODE='22023';
    END IF;
    IF f ? 'language' AND jsonb_typeof(f->'language') IS DISTINCT FROM 'string' THEN
        RAISE EXCEPTION 'language doit etre une chaine' USING ERRCODE='22023';
    END IF;
    IF f ? 'date_range' AND jsonb_typeof(f->'date_range') IS DISTINCT FROM 'object' THEN
        RAISE EXCEPTION 'date_range doit etre un objet' USING ERRCODE='22023';
    END IF;
    IF f ? 'date_range' AND EXISTS (
        SELECT FROM jsonb_object_keys(f->'date_range') key WHERE key NOT IN ('from','to')
    ) THEN
        RAISE EXCEPTION 'date_range accepte from et to' USING ERRCODE='22023';
    END IF;
    IF COALESCE(f->>'date_from', f#>>'{date_range,from}')::timestamp >
       COALESCE(f->>'date_to', f#>>'{date_range,to}')::timestamp THEN
        RAISE EXCEPTION 'La date de debut depasse la date de fin' USING ERRCODE='22023';
    END IF;
END $$;

CREATE OR REPLACE FUNCTION faceted_search(p_filters JSONB)
RETURNS TABLE (post_id INTEGER, title VARCHAR, score INTEGER, tags VARCHAR)
LANGUAGE plpgsql STABLE AS $$
DECLARE f JSONB := COALESCE(p_filters, '{}'::jsonb);
BEGIN
    PERFORM validate_search_filters(f);
    RETURN QUERY SELECT p.id, p.title, p.score, p.tags FROM posts p
    WHERE p.post_type_id = 1
      AND p.score >= COALESCE((f->>'min_score')::integer, -2147483648)
      AND p.creation_date >= COALESCE(
          COALESCE(f->>'date_from',f#>>'{date_range,from}')::timestamp, '-infinity')
      AND p.creation_date < COALESCE(
          COALESCE(f->>'date_to',f#>>'{date_range,to}')::date + INTERVAL '1 day', 'infinity')
      AND (NOT f ? 'has_accepted_answer' OR
           (p.accepted_answer_id IS NOT NULL) = (f->>'has_accepted_answer')::boolean)
      AND (NOT f ? 'metadata' OR p.metadata @> (f->'metadata'))
      AND NOT EXISTS (
          SELECT FROM jsonb_array_elements_text(f->'tags') wanted(tag)
          WHERE NOT EXISTS (SELECT FROM post_tags pt JOIN tags t ON t.id = pt.tag_id
                            WHERE pt.post_id = p.id AND t.tag_name = wanted.tag))
    ORDER BY p.score DESC, p.id;
END $$;

-- RLS reste active : cette fonction s'exécute avec les droits de l'appelant.
CREATE FUNCTION ranked_search(q TEXT, f JSONB DEFAULT '{}')
RETURNS TABLE (post_id INTEGER, title VARCHAR, snippet TEXT, relevance REAL,
              post_score INTEGER, view_count INTEGER, answer_count INTEGER, match_type TEXT)
LANGUAGE sql STABLE
SET pg_trgm.word_similarity_threshold = '0.35'
AS $$
    WITH config AS (
        SELECT search_config_for(COALESCE(f->>'language',
               current_setting('app.search_language', true))) AS cfg
    ), queries AS (
        SELECT cfg, websearch_to_tsquery(cfg, q) AS local_query,
               websearch_to_tsquery('english', q) AS english_query FROM config
    ), exacts AS MATERIALIZED (
        SELECT p.*, CASE WHEN p.search_config = r.cfg THEN r.local_query
                        ELSE r.english_query END AS query,
               'exact'::text AS match_type
        FROM posts p CROSS JOIN queries r
        JOIN faceted_search(f) allowed ON true
        WHERE allowed.post_id = p.id AND (
            (p.search_config = r.cfg AND p.search_vector @@ r.local_query) OR
            (p.search_config = 'english'::regconfig AND p.search_vector @@ r.english_query))
    ), fuzzy AS (
        SELECT p.*, r.english_query AS query, 'fuzzy'::text AS match_type
        FROM posts p CROSS JOIN queries r
        JOIN faceted_search(f) allowed ON true
        WHERE allowed.post_id = p.id AND (SELECT COUNT(*) FROM exacts) < 5
          AND (p.title % q OR q <% p.title)
          AND NOT EXISTS (SELECT FROM exacts e WHERE e.id = p.id)
    ), candidates AS (SELECT * FROM exacts UNION ALL SELECT * FROM fuzzy)
    SELECT p.id, p.title,
           ts_headline(p.search_config,
               regexp_replace(COALESCE(p.body,''), '<[^>]+>', ' ', 'g'), p.query,
               'MaxWords=35, MinWords=15, StartSel=<b>, StopSel=</b>'),
           (CASE WHEN p.match_type = 'exact' THEN
                1.0 + ts_rank_cd(p.search_vector,p.query)
            ELSE 0.5 * word_similarity(q, COALESCE(p.title,'')) END
            + 0.15 * ln(GREATEST(p.score,0)+1)
            + 0.10 * ln(GREATEST(p.view_count,0)+1)
            + 0.10 / (1 + GREATEST(extract(epoch FROM (CURRENT_TIMESTAMP-p.creation_date))
                                   / 31557600.0,0)))::real,
           p.score, p.view_count, p.answer_count, p.match_type
    FROM candidates p
    ORDER BY (p.match_type = 'exact') DESC, 4 DESC, p.id
$$;

\echo '=== Visibilite, roles et cache isole ==='
DO $$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='tenant_moderator') THEN
        CREATE ROLE tenant_moderator NOLOGIN;
    END IF;
END $$;
CREATE FUNCTION current_app_user_id() RETURNS integer LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('app.current_user_id',true),'')::integer
$$;
DROP POLICY posts_tenant_select ON posts;
CREATE POLICY posts_tenant_select ON posts FOR SELECT TO tenant_reader
USING (tenant_id = current_tenant_id() AND
       (visibility = 'public' OR (visibility='private' AND owner_user_id=current_app_user_id())));
CREATE POLICY posts_moderator_select ON posts FOR SELECT TO tenant_moderator
USING (tenant_id = current_tenant_id());
GRANT USAGE ON SCHEMA public TO tenant_moderator;
GRANT CONNECT ON DATABASE stackexchange TO tenant_moderator;
GRANT SELECT ON posts, post_tags, tags TO tenant_reader, tenant_moderator, lab_admin;

CREATE FUNCTION search_scope() RETURNS text LANGUAGE sql STABLE AS $$
    SELECT current_user || ':' || COALESCE(current_tenant_id()::text,'') || ':' ||
           COALESCE(current_app_user_id()::text,'') || ':' ||
           COALESCE(current_setting('app.search_language',true),'en')
$$;
TRUNCATE search_cache, search_log, search_suggestions;
ALTER TABLE search_cache ADD COLUMN scope TEXT NOT NULL DEFAULT search_scope();
ALTER TABLE search_log ADD COLUMN scope TEXT NOT NULL DEFAULT search_scope();
ALTER TABLE search_suggestions DROP CONSTRAINT search_suggestions_suggestion_key;
ALTER TABLE search_suggestions ADD COLUMN scope TEXT NOT NULL DEFAULT search_scope();
ALTER TABLE search_suggestions ADD UNIQUE (scope, suggestion);
ALTER TABLE search_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE search_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE search_suggestions ENABLE ROW LEVEL SECURITY;
CREATE POLICY cache_scope ON search_cache USING (scope=search_scope()) WITH CHECK (scope=search_scope());
CREATE POLICY log_scope ON search_log USING (scope=search_scope()) WITH CHECK (scope=search_scope());
CREATE POLICY suggestion_scope ON search_suggestions USING (scope=search_scope()) WITH CHECK (scope=search_scope());
GRANT SELECT, INSERT, UPDATE ON search_cache, search_suggestions TO tenant_reader, tenant_moderator, lab_admin;
GRANT SELECT, INSERT ON search_log TO tenant_reader, tenant_moderator, lab_admin;
GRANT USAGE ON SEQUENCE search_log_id_seq, search_suggestions_id_seq TO tenant_reader, tenant_moderator, lab_admin;

-- L'invalidation fait partie de l'écriture, y compris lors d'un changement
-- de visibilité. Le chemin fixe protège cette petite fonction privilégiée.
CREATE FUNCTION invalidate_search_cache() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
BEGIN DELETE FROM public.search_cache; RETURN NULL; END $$;
REVOKE ALL ON FUNCTION invalidate_search_cache() FROM PUBLIC;
CREATE TRIGGER invalidate_posts_cache AFTER INSERT OR UPDATE OR DELETE ON posts
FOR EACH STATEMENT EXECUTE FUNCTION invalidate_search_cache();
CREATE TRIGGER invalidate_tags_cache AFTER INSERT OR UPDATE OR DELETE ON post_tags
FOR EACH STATEMENT EXECUTE FUNCTION invalidate_search_cache();

CREATE TRIGGER invalidate_tag_names_cache AFTER UPDATE OR DELETE ON tags
FOR EACH STATEMENT EXECUTE FUNCTION invalidate_search_cache();

CREATE OR REPLACE FUNCTION advanced_search(p_query_text TEXT,
    p_filters JSONB DEFAULT '{}', p_page INTEGER DEFAULT 1, p_page_size INTEGER DEFAULT 20)
RETURNS TABLE (post_id INTEGER, title VARCHAR, snippet TEXT, relevance REAL,
              post_score INTEGER, view_count INTEGER, answer_count INTEGER)
LANGUAGE plpgsql AS $$
DECLARE started timestamptz := clock_timestamp(); h TEXT; results JSONB;
        cached BOOLEAN := false; f JSONB := COALESCE(p_filters,'{}');
BEGIN
    IF p_query_text IS NULL OR btrim(p_query_text)='' OR length(p_query_text)>500 THEN
        RAISE EXCEPTION 'Recherche attendue : 1 a 500 caracteres' USING ERRCODE='22023';
    END IF;
    IF p_page IS NULL OR p_page < 1 OR p_page_size IS NULL OR p_page_size NOT BETWEEN 1 AND 100 THEN
        RAISE EXCEPTION 'Page >= 1 et taille de page entre 1 et 100' USING ERRCODE='22023';
    END IF;
    PERFORM validate_search_filters(f);
    h := encode(digest(jsonb_build_array(search_scope(),lower(btrim(p_query_text)),
                                       f,p_page,p_page_size)::text,'sha256'),'hex');
    SELECT c.results INTO results FROM search_cache c
    WHERE c.query_hash=h AND c.scope=search_scope()
      AND c.created_at > clock_timestamp()-INTERVAL '5 minutes';
    IF FOUND THEN
        cached := true;
        UPDATE search_cache c SET hits=c.hits+1 WHERE c.query_hash=h;
    ELSE
        SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY r.ord),'[]') INTO results
        FROM (
            SELECT s.*, row_number() OVER (
                ORDER BY (s.match_type='exact') DESC,s.relevance DESC,s.post_id) AS ord
            FROM ranked_search(p_query_text,f) s
            ORDER BY (s.match_type='exact') DESC,s.relevance DESC,s.post_id
            LIMIT p_page_size OFFSET (p_page::bigint-1)*p_page_size
        ) r;
        INSERT INTO search_cache (query_hash,query_text,filters,page,page_size,results,scope)
        VALUES (h,p_query_text,f,p_page,p_page_size,results,search_scope())
        ON CONFLICT (query_hash) DO UPDATE
        SET results=EXCLUDED.results, created_at=clock_timestamp(), hits=search_cache.hits+1;
    END IF;
    INSERT INTO search_suggestions (suggestion,scope)
    VALUES (lower(btrim(p_query_text)),search_scope())
    ON CONFLICT (scope,suggestion) DO UPDATE
    SET frequency=search_suggestions.frequency+1,last_used=clock_timestamp();
    INSERT INTO search_log (query_text,filters,result_count,cache_hit,duration_ms,scope)
    VALUES (p_query_text,f,jsonb_array_length(results),cached,
            extract(epoch FROM (clock_timestamp()-started))*1000,search_scope());
    RETURN QUERY SELECT x.post_id,x.title,x.snippet,x.relevance,x.post_score,x.view_count,x.answer_count
    FROM jsonb_to_recordset(results) AS x(post_id integer,title varchar,snippet text,
         relevance real,post_score integer,view_count integer,answer_count integer,ord bigint)
    ORDER BY x.ord;
END $$;

CREATE OR REPLACE FUNCTION search_posts(p_search_query TEXT,p_page INTEGER DEFAULT 1,p_page_size INTEGER DEFAULT 20)
RETURNS TABLE (post_id INTEGER,post_title VARCHAR,snippet TEXT,relevance_score REAL,
              post_score INTEGER,view_count INTEGER,answer_count INTEGER)
LANGUAGE sql VOLATILE AS $$ SELECT * FROM advanced_search(p_search_query,'{}',p_page,p_page_size) $$;
CREATE OR REPLACE FUNCTION smart_search(p_query_text TEXT)
RETURNS TABLE (post_id INTEGER,title VARCHAR,match_type TEXT,score REAL)
LANGUAGE sql STABLE AS $$
    SELECT s.post_id,s.title,s.match_type,s.relevance FROM ranked_search(p_query_text) s
    WHERE NULLIF(btrim(p_query_text),'') IS NOT NULL
    ORDER BY (s.match_type='exact') DESC,s.relevance DESC,s.post_id LIMIT 10
$$;
CREATE OR REPLACE FUNCTION get_search_suggestions(p_partial_query TEXT,p_limit_count INTEGER DEFAULT 10)
RETURNS TABLE (suggestion TEXT,frequency INTEGER,similarity_score REAL)
LANGUAGE sql STABLE AS $$
    SELECT s.suggestion,s.frequency,similarity(s.suggestion,lower(p_partial_query))
    FROM search_suggestions s
    WHERE s.scope=search_scope() AND NULLIF(btrim(p_partial_query),'') IS NOT NULL
      AND (starts_with(s.suggestion,lower(p_partial_query)) OR similarity(s.suggestion,lower(p_partial_query))>=0.20)
    ORDER BY starts_with(s.suggestion,lower(p_partial_query)) DESC,
             s.frequency DESC,similarity(s.suggestion,lower(p_partial_query)) DESC,s.suggestion
    LIMIT LEAST(GREATEST(p_limit_count,1),50)
$$;

\echo '=== Triggers de badges : reponse acceptee et modification de vote ==='
CREATE OR REPLACE FUNCTION trigger_award_badges_from_post() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE accepted_owner INTEGER;
BEGIN
    PERFORM check_and_award_badges(NEW.owner_user_id);
    IF NEW.accepted_answer_id IS NOT NULL THEN
        SELECT owner_user_id INTO accepted_owner FROM posts WHERE id=NEW.accepted_answer_id;
        PERFORM check_and_award_badges(accepted_owner);
    END IF;
    RETURN NULL;
END $$;
CREATE TRIGGER trig_award_badges_post
AFTER INSERT OR UPDATE OF score, view_count, accepted_answer_id, owner_user_id ON posts
FOR EACH ROW EXECUTE FUNCTION trigger_award_badges_from_post();
DROP TRIGGER trig_award_badges_vote ON votes;
CREATE TRIGGER trig_award_badges_vote AFTER INSERT OR UPDATE ON votes
FOR EACH ROW EXECUTE FUNCTION trigger_award_badges_from_vote();

CREATE OR REPLACE FUNCTION update_answer_count() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP IN ('DELETE','UPDATE') AND OLD.post_type_id=2 THEN
        UPDATE posts SET answer_count=GREATEST(answer_count-1,0) WHERE id=OLD.parent_id;
    END IF;
    IF TG_OP IN ('INSERT','UPDATE') AND NEW.post_type_id=2 THEN
        UPDATE posts SET answer_count=answer_count+1 WHERE id=NEW.parent_id;
    END IF;
    RETURN NULL;
END $$;
CREATE TRIGGER trig_update_answer_count
AFTER INSERT OR DELETE ON posts FOR EACH ROW EXECUTE FUNCTION update_answer_count();
CREATE TRIGGER trig_answer_move AFTER UPDATE OF parent_id,post_type_id ON posts
FOR EACH ROW WHEN (OLD.parent_id IS DISTINCT FROM NEW.parent_id OR OLD.post_type_id IS DISTINCT FROM NEW.post_type_id)
EXECUTE FUNCTION update_answer_count();

CREATE TRIGGER trig_audit_posts
AFTER INSERT OR UPDATE OR DELETE ON posts
FOR EACH ROW
EXECUTE FUNCTION audit_posts();

\echo '=== Tableau de bord temps reel et questions montantes ==='
CREATE FUNCTION get_dashboard_metrics() RETURNS JSONB LANGUAGE plpgsql STABLE AS $$
BEGIN
    RETURN jsonb_build_object(
        'questions_visibles',(SELECT COUNT(*) FROM posts WHERE post_type_id=1),
        'recherches',(SELECT COUNT(*) FROM search_log WHERE scope=search_scope()),
        'p95_ms',(SELECT percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms)
                  FROM search_log WHERE scope=search_scope()),
        'taux_cache',(SELECT AVG(cache_hit::integer) FROM search_log WHERE scope=search_scope()));
END;
$$;
CREATE FUNCTION get_rising_questions(p_window INTERVAL DEFAULT INTERVAL '30 days')
RETURNS TABLE(post_id INTEGER,title VARCHAR,recent_votes BIGINT)
LANGUAGE sql STABLE AS $$
    SELECT p.id,p.title,COUNT(*) FROM posts p JOIN votes v ON v.post_id=p.id
    WHERE p.post_type_id=1 AND v.vote_type_id=2
      AND v.creation_date >= CURRENT_TIMESTAMP-p_window
    GROUP BY p.id,p.title ORDER BY COUNT(*) DESC,p.id LIMIT 20
$$;
GRANT SELECT ON votes TO lab_admin;
-- Les vues matérialisées contiennent toutes les données : réservées à l'admin.
GRANT SELECT ON dashboard_posts,search_analytics TO lab_admin;
REVOKE ALL ON user_secrets FROM PUBLIC,tenant_reader,tenant_moderator;
ANALYZE;
SELECT * FROM advanced_search('coffee brewing');
SELECT * FROM advanced_search('coffee brewing');
SELECT * FROM smart_search('expresso');
SELECT get_dashboard_metrics();
REFRESH MATERIALIZED VIEW search_analytics;
SELECT query,calls,round(mean_exec_time::numeric,3) AS moyenne_ms,rows
FROM pg_stat_statements
WHERE query ILIKE '%advanced_search%'
  AND dbid=(SELECT oid FROM pg_database WHERE datname=current_database())
ORDER BY mean_exec_time DESC;
