\set ON_ERROR_STOP on
\pset pager off
\timing on

\echo '=== LAB 01 - verification de la connexion ==='
SELECT version();
SELECT current_database() AS base_actuelle, current_user AS utilisateur_actuel;
SELECT NOW() AS date_serveur;
SHOW max_connections;
SHOW shared_buffers;
SHOW work_mem;
SHOW port;
SHOW data_directory;
SHOW config_file;
SHOW hba_file;

\echo '=== Exercice 1.4 - creation de la table test_users ==='
DROP TABLE IF EXISTS test_users;
CREATE TABLE test_users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
\d test_users

\echo '=== Exercice 1.5 - insertions ==='
INSERT INTO test_users (username, email)
VALUES ('alice', 'alice@example.com');

INSERT INTO test_users (username, email)
VALUES
    ('bob', 'bob@example.com'),
    ('charlie', 'charlie@example.com');

TABLE test_users;

\echo '=== Exercice 1.6 - mise a jour et suppression ==='
UPDATE test_users
SET email = 'alice.new@example.com'
WHERE username = 'alice'
RETURNING *;

DELETE FROM test_users
WHERE username = 'charlie'
RETURNING *;

TABLE test_users;

\echo '=== Exercice 1.7 - transaction annulee ==='
BEGIN;
INSERT INTO test_users (username, email)
VALUES ('dave', 'dave@example.com');
SELECT username, email FROM test_users WHERE username = 'dave';
ROLLBACK;
SELECT COUNT(*) AS dave_apres_rollback
FROM test_users
WHERE username = 'dave';

\echo '=== Exercice 1.7 - transaction validee ==='
BEGIN;
INSERT INTO test_users (username, email)
VALUES ('dave', 'dave@example.com');
COMMIT;
SELECT username, email FROM test_users WHERE username = 'dave';

\echo '=== Defi optionnel - table notes ==='
DROP TABLE IF EXISTS notes;
CREATE TABLE notes (
    note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO notes (title, content)
VALUES
    ('Installation', 'PostgreSQL fonctionne dans Docker.'),
    ('psql', 'Les meta-commandes commencent par un antislash.'),
    ('DDL', 'CREATE TABLE modifie la structure.'),
    ('DML', 'INSERT, UPDATE et DELETE modifient les donnees.'),
    ('Transaction', 'ROLLBACK annule et COMMIT valide.');

SELECT *
FROM notes
WHERE created_at::date = CURRENT_DATE
ORDER BY note_id;

UPDATE notes
SET title = 'Installation PostgreSQL'
WHERE note_id = 1
RETURNING *;

DELETE FROM notes RETURNING note_id;
DROP TABLE notes;

\echo '=== Exercice 1.8 - nettoyage ==='
DROP TABLE test_users;
SELECT COUNT(*) AS tables_restantes_dans_public
FROM pg_tables
WHERE schemaname = 'public';
