\set ON_ERROR_STOP on
\pset pager off
\timing on

\connect blogapp_lab

\echo '=== Exercices 2.1 et 2.2 - schema et relations Pagila ==='
\connect pagila
\dt
\d customer
\d rental
SELECT conrelid::regclass AS table_enfant, conname,
       confrelid::regclass AS table_parent, pg_get_constraintdef(oid) AS relation
FROM pg_constraint
WHERE contype = 'f' AND connamespace = 'public'::regnamespace
ORDER BY conrelid::regclass::text, conname;
\connect blogapp_lab

\echo '=== LAB 02 - exercices DDL dans un schema isole ==='
DROP SCHEMA IF EXISTS lab02_exercices CASCADE;
CREATE SCHEMA lab02_exercices;
SET search_path TO lab02_exercices, public;

\echo '=== Exercice 2.3 - table tags ==='
CREATE TABLE tags (
    tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL UNIQUE,
    slug VARCHAR(50) NOT NULL UNIQUE,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

\echo '=== Exercice 2.5 - ALTER TABLE ==='
ALTER TABLE tags ADD COLUMN description TEXT;
ALTER TABLE tags ADD COLUMN compteur_utilisation INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tags
    ADD CONSTRAINT chk_tags_compteur_non_negatif CHECK (compteur_utilisation >= 0),
    ADD CONSTRAINT chk_tags_nom_longueur CHECK (char_length(trim(nom)) >= 2);
ALTER TABLE tags RENAME COLUMN cree_le TO date_creation;

INSERT INTO tags (nom, slug, description)
VALUES
    ('PostgreSQL', 'postgresql', 'Base de donnees relationnelle'),
    ('Python', 'python', 'Langage de programmation'),
    ('JavaScript', 'javascript', 'Langage du Web')
RETURNING *;

INSERT INTO tags (nom, slug)
VALUES ('PostgreSQL', 'postgresql')
ON CONFLICT (slug) DO NOTHING;

DO $$
BEGIN
    BEGIN
        INSERT INTO tags (nom, slug) VALUES ('X', 'x');
        RAISE EXCEPTION 'Le test devait echouer';
    EXCEPTION WHEN check_violation THEN
        RAISE NOTICE 'OK : un nom de tag trop court est refuse.';
    END;

    BEGIN
        UPDATE tags SET compteur_utilisation = -1 WHERE slug = 'python';
        RAISE EXCEPTION 'Le test devait echouer';
    EXCEPTION WHEN check_violation THEN
        RAISE NOTICE 'OK : un compteur negatif est refuse.';
    END;
END;
$$;

\d tags

\echo '=== Exercice 2.4 - contraintes sur commentaires ==='
CREATE TABLE utilisateurs (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE posts (
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES utilisateurs(user_id) ON DELETE CASCADE,
    titre VARCHAR(200) NOT NULL
);

CREATE TABLE commentaires (
    comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    contenu TEXT NOT NULL,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_commentaires_post
        FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_commentaires_utilisateur
        FOREIGN KEY (user_id) REFERENCES utilisateurs(user_id) ON DELETE RESTRICT,
    CONSTRAINT chk_commentaires_contenu_non_vide
        CHECK (char_length(trim(contenu)) >= 1)
);

INSERT INTO utilisateurs (username) VALUES ('alice'), ('bob');
INSERT INTO posts (user_id, titre) VALUES (1, 'Premier post');
INSERT INTO commentaires (post_id, user_id, contenu)
VALUES (1, 2, 'Commentaire de test');

DO $$
BEGIN
    BEGIN
        DELETE FROM utilisateurs WHERE user_id = 2;
        RAISE EXCEPTION 'Le test devait echouer';
    EXCEPTION WHEN foreign_key_violation OR restrict_violation THEN
        RAISE NOTICE 'OK : ON DELETE RESTRICT protege l auteur du commentaire.';
    END;
END;
$$;

DELETE FROM posts WHERE post_id = 1;
SELECT COUNT(*) AS commentaires_apres_suppression_du_post FROM commentaires;

RESET search_path;
DROP SCHEMA lab02_exercices CASCADE;

\echo '=== Exercices 2.6 a 2.8 - Pagila, dans une transaction annulee ==='
\connect pagila
BEGIN;

SELECT language_id, trim(name) AS langue
FROM language
ORDER BY language_id;

INSERT INTO customer (
    store_id, first_name, last_name, email, address_id, activebool, create_date
)
VALUES (
    1, 'LAB', 'STUDENT', 'lab.student@example.com', 1, TRUE, CURRENT_DATE
)
RETURNING customer_id AS nouveau_customer_id \gset

\echo 'Nouveau client : ' :nouveau_customer_id

INSERT INTO film (
    title, description, release_year, language_id,
    rental_duration, rental_rate, length, replacement_cost, rating
)
VALUES
    ('LAB FILM ALPHA', 'Film de test A', 2024, 5, 3, 2.99, 90, 19.99, 'PG'),
    ('LAB FILM BETA', 'Film de test B', 2024, 5, 4, 3.99, 105, 21.99, 'PG-13'),
    ('LAB FILM GAMMA', 'Film de test C', 2024, 5, 5, 4.99, 120, 24.99, 'R')
RETURNING film_id, title, language_id, rental_rate;

UPDATE customer
SET email = 'mary.smith+lab@example.com'
WHERE customer_id = 1
RETURNING customer_id, first_name, last_name, email;

WITH films_du_magasin_1 AS (
    SELECT DISTINCT i.film_id
    FROM customer c
    JOIN rental r ON r.customer_id = c.customer_id
    JOIN inventory i ON i.inventory_id = r.inventory_id
    WHERE c.store_id = 1
), films_modifies AS (
    UPDATE film f
    SET rental_rate = round(f.rental_rate * 0.90, 2)
    FROM films_du_magasin_1 x
    WHERE x.film_id = f.film_id
    RETURNING f.film_id
)
SELECT COUNT(*) AS films_avec_reduction FROM films_modifies;

DELETE FROM customer
WHERE customer_id = :nouveau_customer_id
RETURNING customer_id, email;

CREATE TEMP TABLE rental_archive (LIKE rental INCLUDING ALL);
-- Location de démonstration sans paiement : le déplacement sera observable
-- même si toutes les anciennes locations du dump ont déjà des paiements.
INSERT INTO rental (rental_date, inventory_id, customer_id, return_date, staff_id)
VALUES (CURRENT_DATE - INTERVAL '10 years', 1, 1,
        CURRENT_DATE - INTERVAL '10 years' + INTERVAL '3 days', 1);

-- payment protège les locations référencées. Une seule instruction déplace
-- les autres : aucune ligne supprimée ne peut être perdue avant l'archivage.
WITH locations_supprimees AS (
    DELETE FROM rental r
    WHERE r.rental_date < CURRENT_DATE - INTERVAL '2 years'
      AND NOT EXISTS (
          SELECT 1
          FROM payment p
          WHERE p.rental_id = r.rental_id
      )
    RETURNING r.*
)
INSERT INTO rental_archive SELECT * FROM locations_supprimees;
SELECT COUNT(*) AS locations_reellement_deplacees FROM rental_archive;
ROLLBACK;

\echo '=== Creation propre de la base BlogApp ==='
\connect blogapp_lab
DROP DATABASE IF EXISTS blogapp WITH (FORCE);
CREATE DATABASE blogapp OWNER labuser;
\connect blogapp

CREATE TABLE utilisateurs (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe_hash VARCHAR(255) NOT NULL,
    prenom VARCHAR(50),
    nom VARCHAR(50),
    bio TEXT,
    avatar_url VARCHAR(500),
    est_actif BOOLEAN NOT NULL DEFAULT TRUE,
    est_verifie BOOLEAN NOT NULL DEFAULT FALSE,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    derniere_connexion TIMESTAMPTZ,
    CONSTRAINT chk_utilisateurs_username_longueur
        CHECK (char_length(trim(username)) >= 3),
    CONSTRAINT chk_utilisateurs_email_format
        CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

CREATE TABLE categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_categories_nom_longueur
        CHECK (char_length(trim(nom)) >= 2)
);

CREATE TABLE posts (
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    category_id INTEGER,
    titre VARCHAR(200) NOT NULL,
    slug VARCHAR(250) NOT NULL UNIQUE,
    extrait TEXT,
    contenu TEXT NOT NULL,
    image_vedette VARCHAR(500),
    statut VARCHAR(20) NOT NULL DEFAULT 'brouillon',
    compteur_vues INTEGER NOT NULL DEFAULT 0,
    publie_le TIMESTAMPTZ,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_posts_utilisateur
        FOREIGN KEY (user_id) REFERENCES utilisateurs(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_posts_categorie
        FOREIGN KEY (category_id) REFERENCES categories(category_id) ON DELETE SET NULL,
    CONSTRAINT chk_posts_statut
        CHECK (statut IN ('brouillon', 'publie', 'archive')),
    CONSTRAINT chk_posts_date_publication
        CHECK (statut <> 'publie' OR publie_le IS NOT NULL),
    CONSTRAINT chk_posts_compteur_vues_non_negatif
        CHECK (compteur_vues >= 0),
    CONSTRAINT chk_posts_contenu_non_vide
        CHECK (char_length(trim(contenu)) >= 1)
);

CREATE TABLE tags (
    tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL UNIQUE,
    slug VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    compteur_utilisation INTEGER NOT NULL DEFAULT 0,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_tags_nom_longueur CHECK (char_length(trim(nom)) >= 2),
    CONSTRAINT chk_tags_compteur_non_negatif CHECK (compteur_utilisation >= 0)
);

CREATE TABLE post_tags (
    post_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_post_tags_post
        FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_post_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags(tag_id) ON DELETE CASCADE
);

CREATE TABLE commentaires (
    comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    parent_id INTEGER,
    contenu TEXT NOT NULL,
    est_approuve BOOLEAN NOT NULL DEFAULT FALSE,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_commentaires_post
        FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_commentaires_utilisateur
        FOREIGN KEY (user_id) REFERENCES utilisateurs(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_commentaires_parent
        FOREIGN KEY (parent_id) REFERENCES commentaires(comment_id) ON DELETE CASCADE,
    CONSTRAINT chk_commentaires_contenu_non_vide
        CHECK (char_length(trim(contenu)) >= 1)
);

-- PostgreSQL ne cree pas automatiquement les index sur les colonnes FK.
CREATE INDEX idx_posts_utilisateur ON posts(user_id);
CREATE INDEX idx_posts_categorie ON posts(category_id);
CREATE INDEX idx_posts_statut ON posts(statut);
CREATE INDEX idx_posts_publie ON posts(publie_le DESC) WHERE statut = 'publie';
CREATE INDEX idx_posts_cree ON posts(cree_le DESC);
CREATE INDEX idx_post_tags_tag ON post_tags(tag_id);
CREATE INDEX idx_commentaires_post ON commentaires(post_id, cree_le);
CREATE INDEX idx_commentaires_utilisateur ON commentaires(user_id, cree_le);
CREATE INDEX idx_commentaires_parent ON commentaires(parent_id);
CREATE INDEX idx_commentaires_approuve
    ON commentaires(post_id, cree_le) WHERE est_approuve = TRUE;

CREATE OR REPLACE FUNCTION definir_date_modification()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.modifie_le := NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trig_utilisateurs_modifie_le
BEFORE UPDATE ON utilisateurs
FOR EACH ROW EXECUTE FUNCTION definir_date_modification();

CREATE TRIGGER trig_posts_modifie_le
BEFORE UPDATE ON posts
FOR EACH ROW EXECUTE FUNCTION definir_date_modification();

CREATE TRIGGER trig_commentaires_modifie_le
BEFORE UPDATE ON commentaires
FOR EACH ROW EXECUTE FUNCTION definir_date_modification();

\echo '=== Donnees de test BlogApp pour les LAB 03 et 04 ==='
INSERT INTO utilisateurs (
    username, email, mot_de_passe_hash, prenom, nom, bio,
    est_actif, est_verifie, cree_le, derniere_connexion
)
VALUES
    ('alice', 'alice@example.com', 'hash_alice', 'Alice', 'Martin', 'Autrice PostgreSQL', TRUE, TRUE, NOW() - INTERVAL '18 months', NOW() - INTERVAL '1 day'),
    ('bob', 'bob@example.com', 'hash_bob', 'Bob', 'Durand', 'Developpeur Web', TRUE, TRUE, NOW() - INTERVAL '14 months', NOW() - INTERVAL '3 days'),
    ('charlie', 'charlie@example.com', 'hash_charlie', 'Charlie', 'Bernard', 'Lecteur regulier', TRUE, FALSE, NOW() - INTERVAL '10 months', NOW() - INTERVAL '7 days'),
    ('diana', 'diana@example.com', 'hash_diana', 'Diana', 'Petit', 'Data analyst', TRUE, TRUE, NOW() - INTERVAL '6 months', NOW() - INTERVAL '2 days'),
    ('eric', 'eric@example.com', 'hash_eric', 'Eric', 'Robert', 'Compte inactif', FALSE, FALSE, NOW() - INTERVAL '3 years', NOW() - INTERVAL '2 years'),
    ('farah', 'farah@example.com', 'hash_farah', 'Farah', 'Leroy', 'Nouvelle membre', TRUE, FALSE, NOW() - INTERVAL '20 days', NOW() - INTERVAL '5 hours');

INSERT INTO categories (nom, slug, description)
VALUES
    ('Programmation', 'programmation', 'Developpement logiciel'),
    ('Bases de donnees', 'bases-de-donnees', 'SQL et modelisation'),
    ('Tutoriels', 'tutoriels', 'Guides pas a pas'),
    ('Actualites', 'actualites', 'Nouveautes techniques'),
    ('Sans post', 'sans-post', 'Categorie volontairement vide');

INSERT INTO tags (nom, slug, description)
VALUES
    ('PostgreSQL', 'postgresql', 'SGBD PostgreSQL'),
    ('SQL', 'sql', 'Langage SQL'),
    ('Tutoriel', 'tutoriel', 'Contenu pedagogique'),
    ('Performance', 'performance', 'Optimisation'),
    ('Docker', 'docker', 'Conteneurs'),
    ('Debutant', 'debutant', 'Niveau debutant'),
    ('Inutilise', 'inutilise', 'Tag sans post');

INSERT INTO posts (
    user_id, category_id, titre, slug, extrait, contenu,
    statut, compteur_vues, publie_le, cree_le
)
VALUES
    (1, 2, 'Bien debuter avec PostgreSQL', 'getting-started-postgresql', 'Installation et premieres requetes', 'PostgreSQL est un SGBD relationnel puissant. Ce tutoriel explique les bases.', 'publie', 1250, NOW() - INTERVAL '400 days', NOW() - INTERVAL '405 days'),
    (1, 2, 'Comprendre les index PostgreSQL', 'comprendre-index-postgresql', 'B-tree, GIN et BRIN', 'Un index accelere certaines lectures mais coute sur les ecritures.', 'publie', 830, NOW() - INTERVAL '40 days', NOW() - INTERVAL '45 days'),
    (1, 3, 'Transactions SQL sans stress', 'transactions-sql', 'BEGIN, COMMIT et ROLLBACK', 'Une transaction regroupe plusieurs operations de facon atomique.', 'publie', 260, NOW() - INTERVAL '2 days', NOW() - INTERVAL '4 days'),
    (2, 1, 'Lancer PostgreSQL avec Docker', 'postgresql-docker', 'Un environnement isole', 'Docker permet de lancer PostgreSQL sans modifier le systeme hote.', 'publie', 640, NOW() - INTERVAL '15 days', NOW() - INTERVAL '18 days'),
    (2, 1, 'API Web et SQL', 'api-web-sql', 'Requetes parametrees', 'Les requetes parametrees evitent les injections SQL.', 'publie', 410, NOW() - INTERVAL '70 days', NOW() - INTERVAL '75 days'),
    (2, 4, 'PostgreSQL 16 en pratique', 'postgresql-16-pratique', 'Fonctionnalites utiles', 'PostgreSQL 16 apporte des ameliorations de performance et de monitoring.', 'archive', 510, NULL, NOW() - INTERVAL '400 days'),
    (4, 2, 'Analyser un plan EXPLAIN', 'analyser-plan-explain', 'Lire un plan simplement', 'EXPLAIN ANALYZE execute la requete et montre les temps reels.', 'publie', 980, NOW() - INTERVAL '6 days', NOW() - INTERVAL '9 days'),
    (4, 3, 'Fonctions fenetre', 'fonctions-fenetre', 'ROW_NUMBER, RANK et LAG', 'Les fonctions fenetre calculent sans reduire le nombre de lignes.', 'publie', 720, NOW() - INTERVAL '25 days', NOW() - INTERVAL '30 days'),
    (4, 2, 'JSONB ou tables relationnelles', 'jsonb-ou-relationnel', 'Choisir le bon modele', 'JSONB est utile pour les attributs flexibles, pas pour tout remplacer.', 'brouillon', 25, NULL, NOW() - INTERVAL '3 days'),
    (3, 3, 'Mon premier SELECT', 'mon-premier-select', 'Selectionner des colonnes', 'SELECT lit les donnees sans les modifier.', 'publie', 95, NOW() - INTERVAL '1 day', NOW() - INTERVAL '2 days'),
    (1, 2, 'Optimiser les jointures', 'optimiser-jointures', 'Eviter les multiplications de lignes', 'Il faut agreger au bon niveau avant de joindre plusieurs relations un-a-plusieurs.', 'brouillon', 15, NULL, NOW() - INTERVAL '1 day'),
    (2, 4, 'Veille technique a publier', 'veille-technique', 'Brouillon de veille', 'Contenu en preparation.', 'brouillon', 0, NULL, NOW() - INTERVAL '2 hours');

INSERT INTO post_tags (post_id, tag_id)
VALUES
    (1, 1), (1, 2), (1, 3), (1, 6),
    (2, 1), (2, 2), (2, 4),
    (3, 2), (3, 3),
    (4, 1), (4, 5), (4, 3),
    (5, 2),
    (6, 1),
    (7, 1), (7, 4),
    (8, 2), (8, 3),
    (9, 1),
    (10, 2), (10, 6),
    (11, 2), (11, 4);

INSERT INTO commentaires (
    post_id, user_id, parent_id, contenu, est_approuve, cree_le
)
VALUES
    (1, 3, NULL, 'Enfin une explication claire.', TRUE, NOW() - INTERVAL '399 days'),
    (1, 2, 1, 'Merci pour ton retour.', TRUE, NOW() - INTERVAL '398 days'),
    (1, 4, NULL, 'La partie sur psql est utile.', TRUE, NOW() - INTERVAL '390 days'),
    (2, 3, NULL, 'Peux-tu parler des index partiels ?', TRUE, NOW() - INTERVAL '35 days'),
    (2, 1, 4, 'Oui, ce sera le prochain exemple.', TRUE, NOW() - INTERVAL '34 days'),
    (3, 6, NULL, 'ROLLBACK m a sauvee.', TRUE, NOW() - INTERVAL '1 day'),
    (4, 1, NULL, 'Attention au conflit sur le port 5432.', TRUE, NOW() - INTERVAL '14 days'),
    (7, 2, NULL, 'Tres bon exemple EXPLAIN.', TRUE, NOW() - INTERVAL '5 days'),
    (7, 3, NULL, 'Je voudrais un exemple avec BUFFERS.', FALSE, NOW() - INTERVAL '4 days'),
    (8, 1, NULL, 'LAG est vraiment pratique.', TRUE, NOW() - INTERVAL '20 days'),
    (10, 2, NULL, 'Bienvenue dans SQL !', TRUE, NOW() - INTERVAL '12 hours');

UPDATE tags t
SET compteur_utilisation = x.nombre
FROM (
    SELECT tag_id, COUNT(*)::INTEGER AS nombre
    FROM post_tags
    GROUP BY tag_id
) x
WHERE x.tag_id = t.tag_id;

\echo '=== Verification du schema BlogApp ==='
\dt
\d posts
SELECT
    conrelid::regclass AS table,
    conname AS contrainte,
    pg_get_constraintdef(oid) AS definition
FROM pg_constraint
WHERE connamespace = 'public'::regnamespace
ORDER BY conrelid::regclass::text, conname;

SELECT
    (SELECT COUNT(*) FROM utilisateurs) AS utilisateurs,
    (SELECT COUNT(*) FROM posts) AS posts,
    (SELECT COUNT(*) FROM commentaires) AS commentaires,
    (SELECT COUNT(*) FROM tags) AS tags;

\echo '=== Defis LAB 02 - operations annulees apres verification ==='
BEGIN;
INSERT INTO posts (user_id, category_id, titre, slug, contenu)
SELECT 1, 2, 'Post supplementaire ' || n, 'defi-post-' || n,
       'Exemple pour pratiquer les modifications de donnees.'
FROM generate_series(1, 10) n
RETURNING post_id, titre;
UPDATE posts
SET statut = 'publie', publie_le = COALESCE(publie_le, NOW())
WHERE statut = 'brouillon'
RETURNING post_id, statut, publie_le;
DELETE FROM tags WHERE compteur_utilisation = 0 RETURNING tag_id, nom;
INSERT INTO tags (nom, slug, description)
VALUES ('PostgreSQL', 'postgresql', 'Description mise a jour par UPSERT')
ON CONFLICT (slug) DO UPDATE SET description = EXCLUDED.description
RETURNING *;
ROLLBACK;
